### ISSUE TITLE
Few validations missing for createjob form

### ISSUE THREAD

**Issue by meghakundu** [samiulislamsharan/JobSphere#1]
There might be an error in adding validations for the form as two of them were missing. And else when we opt for changing profile picture. Rest is ought to be ok.  @samiulislamsharan

**Comment by samiulislamsharan** [comment]
Hi @meghakundu 

Thanks for reporting the potential issue with form validations. I'd be glad to look into this further.

Could you please elaborate on the two missing validations you found? Any additional details you can provide about the specific forms and fields involved would be extremely helpful.

In the meantime, I'll double-check the validation logic for both adding validations and changing profile pictures.

Also, since this is an open-source project, you're more than welcome to create a pull request to fix the validations directly!  We appreciate any contributions to the codebase.

If you're not familiar with creating pull requests, here are some helpful resources:

GitHub Docs: https://docs.github.com/articles/creating-a-pull-request
A guide for beginners: https://youtu.be/8lGpZkjnkt4?si=lB4y33HedL_39HRh
Let me know if you have any questions or if there's anything I can assist you with!

Thanks ❤️,

@samiulislamsharan

**Comment by meghakundu** [comment]
> Hi @meghakundu
> 
> Thanks for reporting the potential issue with form validations. I'd be glad to look into this further.
> 
> Could you please elaborate on the two missing validations you found? Any additional details you can provide about the specific forms and fields involved would be extremely helpful.
> 
> In the meantime, I'll double-check the validation logic for both adding validations and changing profile pictures.
> 
> Also, since this is an open-source project, you're more than welcome to create a pull request to fix the validations directly! We appreciate any contributions to the codebase.
> 
> If you're not familiar with creating pull requests, here are some helpful resources:
> 
> GitHub Docs: https://docs.github.com/articles/creating-a-pull-request A guide for beginners: https://youtu.be/8lGpZkjnkt4?si=lB4y33HedL_39HRh Let me know if you have any questions or if there's anything I can assist you with!
> 
> Thanks ❤️,
> 
> @samiulislamsharan

you may check in the form itself for which two ajax errors coming for the particular fields: company_location and company_website. And hence try!
